//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace zoodb
{


    public partial class updateEmployee
    {

      
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

       
        protected global::System.Web.UI.WebControls.TextBox emFnam;
        
        protected global::System.Web.UI.WebControls.TextBox emLnam;

        protected global::System.Web.UI.WebControls.DropDownList emExdd;
       
        protected global::System.Web.UI.WebControls.DropDownList jbUpdd;


        protected global::System.Web.UI.HtmlControls.HtmlGenericControl ueLabel;
    }
}
