//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zoodb
{


    public partial class updateAnimal
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.TextBox amName;

        protected global::System.Web.UI.WebControls.DropDownList SelectH;

        protected global::System.Web.UI.WebControls.DropDownList ddExh;

        protected global::System.Web.UI.WebControls.DropDownList ddDiet;
       
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl labelAnimUp;
    }
}
